- name: variables from inventory
  hosts: local
  connection: local
  task:
  - name: print course information
    ansible.builtin.debug:
     msg: "Hello I am learning {{COURSE}}, duration: {{DURATION}}, trainer is: {{TRAINER}}"