- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    DURATION: 120
    COURSE: "Devsecops with AWS"
    IS_LIVE: true
    TOOLS: 
    - linux
    - shell
    - Ansible
    CONCEPTS:
      CI: Jenkins
      SCRIPTNG: "Shell, Ansible, Terraform, Python"
  tasks:
  - name: Print course information
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, duration: {{DURATION}}, Is_live?: {{IS_LIVE}}, Tools are: {{TOOLS}}, Concepts are: {{CONCEPTS}}"