- name: Playbook control using ansible facts
  hosts: frontend
  become: yes 
  task:
  - name: install nginx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: Present 
    when: if ansible_os_family == "RedHat"

    - name: install nginx if debian
    ansible.builtin.apt:
      name: nginx
      state: Present 
    when: if ansible_os_family == "Debian"