- name: install packages
  hosts: frontend
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.packages:
     msg: "{{item}}"
     state: installed
    loops:
    - mysql
    - nginx
    - zip
    
