- name: functions
  hosts: local
  connection: local
  vars:
    Persons: "Ramesh,Suresh,Raheem,Joseph"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ persons }}"