- name: functions
  hosts: local
  connection: local
  vars: 
    persons: "Ramesh,Raheem,Suresh,Joseph"
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello, {{ persons | split(',') }}"

