- name: functions
  hosts: local
  connection: local
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ person | default(Suresh) }}"

  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ persons }}"