- name: shell vs command
  hosts: frontend
  tasks:
  - name: redirect ls output to a file
    ansible.builtin.command: "ls -ltr 
    register: command_result

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ command_result }}"